Issue 24/split schema definitions
dscnitrourkela/project-avocado-web pull request #27
Opened 2020-10-03 05:15 UTC by justemoilouise

**Related issue:** https://github.com/dscnitrourkela/project-avocado-web/issues/24

**Description**
- Split schema definitions into types, queries and mutations
- Update `schema.js` to reference definitions from split files

2020-10-04 19:14 UTC, riteshsp2000 requested changes

2020-10-04 19:14 UTC, riteshsp2000 commented on server/schema/schema.js
>  module.exports = new GraphQLSchema({
GraphQLSchema is undefined here. Hence build is failing.

2020-10-05 06:58 UTC, DesignrKnight commented
@riteshsp2000 
You will review, isn't it?

2020-10-05 07:06 UTC, riteshsp2000 approved these changes

2020-10-05 07:41 UTC, merged

2020-10-05 11:48 UTC, riteshsp2000 commented
@all-contributors please add @justemoilouise  for code

2020-10-05 12:33 UTC, riteshsp2000 commented
@justemoilouise Hey. There's been a slight issue while resolving the conflicts. Could you send a pr again?

2020-12-03 06:41 UTC, DesignrKnight commented
### Hacktoberfest Thank You from NIT Rourkela community
It was a super fun experience in Hacktoberfest with you. We hope you also had fun and amazing learning. We look forward to you in our upcoming sessions and events as part of the community. 
You can join our Slack community at http://bit.ly/NITRDevs

**As a token of our gratitude, we have set up digital badges of recognition for our contributors from Hacktoberfest. 
Do claim yours at https://live.dscnitrourkela.org/**

Thanks and Cheers!
Stay Safe